### ISSUE TITLE
Some registers not highlighted

### ISSUE THREAD

**Issue by lukamac** [zhuanhao-wu/vscode-riscv-support#9]
Registers x1, x26, and x27 aren't being highlighted.
I've looked at the [grammar file](syntaxes/riscv.tmLanguage) and found the regex that recognizes registers:
`<string>\b(x(0|[2-9]|1[0-9]|2[0-5]|2[89]|3[0-1]))\b</string>`

It's clear that those registers were intentionally omitted, so my question is: what is the rationale behind that?

**Comment by zhuanhao-wu** [comment]
Thank you for raising the issue and this is a bug in the grammar.
The grammar is adapted from MIPS and register 1/26/27 in MIPS are reserved registers but they should be highlighted in RISC-V.
